// Auth Actions
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Gym Actions
export const FETCH_PENDING_GYMS_REQUEST = "FETCH_PENDING_GYMS_REQUEST";
export const FETCH_PENDING_GYMS_SUCCESS = "FETCH_PENDING_GYMS_SUCCESS";
export const FETCH_PENDING_GYMS_FAILURE = "FETCH_PENDING_GYMS_FAILURE";

// Amenties Actions
export const ADD_AMENITY_REQUEST = "ADD_AMENITY_REQUEST";
export const ADD_AMENITY_SUCCESS = "ADD_AMENITY_SUCCESS";
export const ADD_AMENITY_FAILURE = "ADD_AMENITY_FAILURE";

export const FETCH_AMENITIES_REQUEST = "FETCH_AMENITIES_REQUEST";
export const FETCH_AMENITIES_SUCCESS = "FETCH_AMENITIES_SUCCESS";
export const FETCH_AMENITIES_FAILURE = "FETCH_AMENITIES_FAILURE";
