// Auth Actions
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Gym Actions
export const FETCH_PENDING_GYMS_REQUEST = "FETCH_PENDING_GYMS_REQUEST";
export const FETCH_PENDING_GYMS_SUCCESS = "FETCH_PENDING_GYMS_SUCCESS";
export const FETCH_PENDING_GYMS_FAILURE = "FETCH_PENDING_GYMS_FAILURE";